#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase0

rm -r ITHACAoutput
rm -r runs
rm -r evaluation
rm -r pitzDaily.vtu pitzDaily.zip

#------------------------------------------------------------------------------
