#!/bin/bash
# Usage: ./Allrun $cores (e.g. ./Allrun 16)
#------------------------------------------------------------------------------
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------


if [ -z "$1" ]
  then
    OFFLINE_CORES=1
else
    OFFLINE_CORES=$1
fi

NAME=$(basename "$(pwd)")

echo "######################################"
echo "# CASE: pitzDaily                    #"
echo "######################################"

echo Preprocessing...
restore0Dir > log.restore 2>&1
blockMesh > log.blockMesh 2>&1
echo Running CFD workflow...
./scripts/samples.sh $OFFLINE_CORES > log.samples 2>&1
echo Building ROM...
./scripts/rom.sh > log.rom 2>&1
echo Running evaluation...
./scripts/evaluation.sh $OFFLINE_CORES > log.evaluation 2>&1
